import { useState, useEffect, useRef } from 'react';
import { io } from 'socket.io-client';
import './App.css';
import * as Y from 'yjs';

const suggestedRooms = ['General', 'Planning', 'Design Review'];

function App() {
  const [message, setMessage] = useState('');
  const [socket, setSocket] = useState(null);

  const [isSomeoneTyping, setIsSomeoneTyping] = useState(false);
  const [typerName, setTyperName] = useState('');

  const [nameInput, setNameInput] = useState('');
  const [onlineCount, setOnlineCount] = useState(0);
  // Restore the username from localStorage when the app loads
  const [userName, setUserName] = useState(
    () => localStorage.getItem('userName') || ''
  );

  const [roomInput, setRoomInput] = useState('');
  // Restore the last room from localStorage
  const [currentRoom, setCurrentRoom] = useState(
    () => localStorage.getItem('currentRoom') || ''
  );

  const [activeUsersList, setActiveUsersList] = useState([]);

  const ydocRef = useRef(null);
  const ytextRef = useRef(null);
  const currentRoomRef = useRef(currentRoom);
  const resetYDocRef = useRef(() => {});

  const isTypingLocally = useRef(false);
  const typingTimeout = useRef(null);

  /*
   * Create a persistent session ID.
   * socket.id is temporary and changes whenever the socket reconnects.
   * sessionId stays the same for this browser session.
   */
  const sessionId = useRef(
    localStorage.getItem('sessionId') || crypto.randomUUID()
  );

  useEffect(() => {
    localStorage.setItem('sessionId', sessionId.current);
  }, []);

  useEffect(() => {
    currentRoomRef.current = currentRoom;
  }, [currentRoom]);

  useEffect(() => {
    if (!userName) return;

    const socketInstance = io('http://localhost:3500', {
      transports: ['websocket'],
      auth: {
        username: userName,
        sessionId: sessionId.current,
      },
      // Explicitly enable Socket.IO reconnection
      reconnection: true,
      reconnectionAttempts: Infinity,
      reconnectionDelay: 1000,
    });

    setSocket(socketInstance);

    let activeYDoc = null;
    let activeYText = null;
    
    const handleYTextChange = () => {
      const currentYText = ytextRef.current;
      if (!currentYText) {
        return;
      }
      setMessage(currentYText.toString());
    };

    /*
    * -------------------------------------------------------
    * Yjs -> Socket.IO
    *
    * Whenever THIS CLIENT makes a local Yjs change,
    * send the binary update to the server.
    *
    * Remote updates are marked with origin "remote",
    * so we don't send them back to the server.
    * -------------------------------------------------------
    */
    const handleYUpdate = (update, origin) => {
      if (origin === 'remote') {
        return;
      }
      const room = currentRoomRef.current;

      if (!socketInstance.connected || !room) {
        return;
      }

      socketInstance.emit('yjs_update', {
        room,
        update: Array.from(update)
      });
    };

    const resetLocalYDoc = () => {
      if (activeYText) {
        activeYText.unobserve(handleYTextChange);
      }
      if (activeYDoc) {
        activeYDoc.off('update', handleYUpdate);
        activeYDoc.destroy();
      }

      const nextYDoc = new Y.Doc();
      const nextYText = nextYDoc.getText('editor');

      nextYText.observe(handleYTextChange);
      nextYDoc.on('update', handleYUpdate);

      activeYDoc = nextYDoc;
      activeYText = nextYText;
      ydocRef.current = nextYDoc;
      ytextRef.current = nextYText;

      setMessage('');
    };

    resetYDocRef.current = resetLocalYDoc;
    resetLocalYDoc();

    /* Socket.IO -> Yjs
    *
    * Receive a Yjs update generated by another client.
    */
    socketInstance.on('yjs_update', (update) => {
      const currentYDoc = ydocRef.current;
      if (!currentYDoc) {
        return;
      }
      const binaryUpdate = new Uint8Array(update);
      Y.applyUpdate(currentYDoc, binaryUpdate, 'remote');
    });

    /*
     * -------------------------------------------------------
     * Initial document state when joining/rejoining
     * -------------------------------------------------------
     */
    socketInstance.on('yjs_sync', (update) => {
      const currentYDoc = ydocRef.current;
      if (!currentYDoc) {
        return;
      }
      const binaryUpdate = new Uint8Array(update);
      Y.applyUpdate(currentYDoc, binaryUpdate, 'remote');
    });


    /*
     * This event fires when:
     * 1. The initial connection is established
     * 2. The socket reconnects after a network failure
     *
     * We use it to rejoin the saved room.
     */
    socketInstance.on('connect', () => {
      console.log('Connected:', socketInstance.id);
      const savedRoom = localStorage.getItem('currentRoom');
      if (savedRoom) {
        setCurrentRoom(savedRoom);
        socketInstance.emit('join_room', savedRoom);
      }
    });

    // socketInstance.on('receive_text_update', (data) => {
    //   setMessage(data);
    // });

    socketInstance.on('room_users_list', (namesArray) => {
      setActiveUsersList(namesArray);
    });

    socketInstance.on('room_user_count', (count) => {
      setOnlineCount(count);
    });

    socketInstance.on('user_typing', (data) => {
      console.log(`User ${data.username} is typing: ${data.isTyping}`);
      setTyperName(data.username);
      setIsSomeoneTyping(data.isTyping);
    });

    socketInstance.on('disconnect', (reason) => {
      console.log('Disconnected:', reason);
    });

    socketInstance.on('connect_error', (error) => {
      console.error('Socket connection error:', error.message);
    });

    return () => {
      socketInstance.disconnect();

      if (activeYText) {
        activeYText.unobserve(handleYTextChange);
      }
      if (activeYDoc) {
        activeYDoc.off('update', handleYUpdate);
        activeYDoc.destroy();
      }
      resetYDocRef.current = () => {};

      if (typingTimeout.current) {
        clearTimeout(typingTimeout.current);
      }
    };
  }, [userName]);

  const handleSetName = (e) => {
    e.preventDefault();
    const trimmedName = nameInput.trim();
    if (!trimmedName) {
      return;
    }
    // Save the username so it survives a browser refresh
    localStorage.setItem('userName', trimmedName);
    setUserName(trimmedName);
  };

  const handleJoinRoom = (e) => {
    e.preventDefault();
    const trimmedRoom = roomInput.trim();

    if (!trimmedRoom || !socket) {
      return;
    }

    resetYDocRef.current();
    setCurrentRoom(trimmedRoom);
    // Save the room so it survives a browser refresh
    localStorage.setItem('currentRoom', trimmedRoom);
    socket.emit('join_room', trimmedRoom);
  };

  /*
  * -------------------------------------------------------
  * Find the difference between old text and new text
  * -------------------------------------------------------
  * This allows our textarea to work with Y.Text.
  *
  * Example:
  * old: Hello world
  * new: Hello beautiful world
  *
  * result:
  * insert "beautiful " at position 6
  */

  const getTextDifference = (oldText, newText) => {
    let start = 0;

    while(
      start < oldText.length &&
      start < newText.length &&
      oldText[start] === newText[start]
    ) {
      start++;
    }

    let oldEnd = oldText.length - 1;
    let newEnd = newText.length - 1;

    while (
      oldEnd >= start &&
      newEnd >= start &&
      oldText[oldEnd] === newText[newEnd]
    ) {
      oldEnd--;
      newEnd--;
    }

    const deleteCount = oldEnd >= start ? oldEnd - start + 1 : 0;
    const insertText = newEnd >= start ? newText.slice(start, newEnd+1) : '';

    return {index:start, deleteCount, insertText};
  };

  const handleChange = (e) => {
    const newValue = e.target.value;
    const ytext = ytextRef.current;

    if (!ytext || !currentRoom) {
      setMessage(newValue);
      return;
    }

    const oldValue = ytext.toString();

    const { index, deleteCount, insertText } = getTextDifference(oldValue, newValue);

    /*
    * Apply the entire local change inside one Yjs transaction.
    */

    ydocRef.current.transact(() => {
      if(deleteCount > 0) {
        ytext.delete(index, deleteCount);
      }
      if(insertText) {
        ytext.insert(index, insertText);
      }
    }, 'local');

    if (socket && currentRoom) {
      // socket.emit('text_change', { room: currentRoom, value });

      if (!isTypingLocally.current) {
        isTypingLocally.current = true;
        socket.emit('typing', { room: currentRoom, username: userName });
      }
      if (typingTimeout.current) {
        clearTimeout(typingTimeout.current);
      }

      typingTimeout.current = setTimeout(() => {
        socket.emit('stop_typing', { room: currentRoom, username: userName });
        isTypingLocally.current = false;
      }, 1500);
    }
  };

  const handleLeaveRoom = () => {
    if (!socket || !currentRoom) return;

    resetYDocRef.current();

    socket.emit('leave_room', currentRoom);

    setCurrentRoom('');
    setMessage('');
    setActiveUsersList([]);
    setOnlineCount(0);
    setIsSomeoneTyping(false);
    setTyperName('');

    localStorage.removeItem('currentRoom');
  };

  const initials = userName
    ? userName
        .split(' ')
        .filter(Boolean)
        .slice(0, 2)
        .map((part) => part[0].toUpperCase())
        .join('')
    : 'U';

  return (
    <div className="app-shell">
      <div className="workspace-panel">
        <header className="topbar">
          <div className="brand-block">
            <div className="brand-mark">S</div>
            <div>
              <p className="brand-label">SyncRoom</p>
              <span className="brand-subtitle">Realtime collaboration</span>
            </div>
          </div>
        </header>

        <div className="main-content">
          <aside className="side-container">
            <div className="sidebar-section">
              <div className="sidebar-heading">
                <p className="sidebar-label">Profile</p>
                <span className={`status-pill ${userName ? 'active' : 'idle'}`}>
                  {userName ? 'Ready' : 'Pending'}
                </span>
              </div>

              <div className="sidebar-card profile-card">
                <div className="profile-identity">
                  <div className="profile-avatar">{initials}</div>
                  <div>
                    <h4>{userName || 'Add your name'}</h4>
                    <p>{userName ? 'Connected to the shared workspace.' : 'Set your identity for teammates.'}</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="sidebar-section">
              <div className="sidebar-heading">
                <p className="sidebar-label">Room</p>
                <span className={`status-pill ${currentRoom ? 'active' : 'idle'}`}>
                  {currentRoom ? 'Joined' : 'Waiting'}
                </span>
              </div>
              <div className="sidebar-card">
                <h4>{currentRoom || 'Join a room'}</h4>
                <p>
                  {currentRoom
                    ? `${onlineCount} ${onlineCount === 1 ? 'person is' : 'people are'} in this room.`
                    : 'Choose a shared room to start collaborating.'}
                </p>
              </div>
            </div>

            <div className="sidebar-section">
              <p className="sidebar-label">People</p>
              {currentRoom ? (
                <div className="sidebar-card sidebar-card-compact">
                  {activeUsersList.length > 0 ? (
                    <ul className="user-list">
                      {activeUsersList.map((name) => (
                        <li key={name}>
                          <span className="user-dot" />
                          {name}
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <p>Waiting for collaborators to join this room.</p>
                  )}
                </div>
              ) : (
                <div className="sidebar-card sidebar-card-compact sidebar-card-muted">
                  <p>Collaborators will appear here after you join a room.</p>
                </div>
              )}
            </div>
          </aside>

          <main className="msg-container">
            {!userName && (
              <section className="empty-panel">
                <div className="onboarding-copy">
                  <span className="step-badge">Step 1</span>
                  <h4>Set your identity</h4>
                  <p>Choose a name so your teammates know who is editing in real time.</p>
                </div>

                <form className="inline-form" onSubmit={handleSetName}>
                  <input
                    type="text"
                    className="text-input"
                    value={nameInput}
                    onChange={(e) => setNameInput(e.target.value)}
                    placeholder="Enter your display name"
                  />

                  <button type="submit" disabled={!nameInput.trim()}>
                    Save name
                  </button>
                </form>
              </section>
            )}

            {userName && !currentRoom && (
              <section className="empty-panel">
                <div className="onboarding-copy">
                  <span className="step-badge">Step 2</span>
                  <h4>Choose a room</h4>
                  <p>Sync a shared space with the people working on the same document.</p>
                </div>

                <form className="inline-form" onSubmit={handleJoinRoom}>
                  <input
                    type="text"
                    className="text-input"
                    value={roomInput}
                    onChange={(e) => setRoomInput(e.target.value)}
                    placeholder="Enter room name"
                  />
                  <button type="submit" disabled={!roomInput.trim()}>
                    Join room
                  </button>
                </form>

                <div className="suggested-rooms">
                  {suggestedRooms.map((room) => (
                    <button
                      key={room}
                      type="button"
                      className="room-chip"
                      onClick={() => setRoomInput(room)}
                    >
                      {room}
                    </button>
                  ))}
                </div>
              </section>
            )}

            {currentRoom && (
              <div className="editor-shell">
                <div className="roomHeader">
                  <div className="room-title-wrap">
                    <span className="room-label">Room</span>
                    <h3>{currentRoom}</h3>
                  </div>
                  <button type="button" className="btn" onClick={handleLeaveRoom}>
                    Leave room
                  </button>
                </div>

                <div className="collab-toolbar">
                  <div className="presence-pill">
                    <span className="presence-dot" />
                    {onlineCount} {onlineCount === 1 ? 'person' : 'people'} online
                  </div>
                  <div className="presence-list">
                    {activeUsersList.length > 0 ? activeUsersList.join(' • ') : 'No one else has joined yet'}
                  </div>
                </div>

                <div className="editor-meta">
                  <p>Updates are shared instantly across the room.</p>
                </div>

                <textarea
                  id="msg"
                  className="msg-box"
                  value={message}
                  onChange={handleChange}
                  placeholder="Type something here..."
                  spellCheck="false"
                />

                {isSomeoneTyping && (
                  <div className="typing-indicator">
                    <span className="typing-dot" />
                    {typerName} is typing...
                  </div>
                )}
              </div>
            )}
          </main>
        </div>
      </div>
    </div>
  );
}

export default App;